path = '/' # defaults to /
queries = [
  'project name' # optional regex validation
]
replacements = [
  'TODO'
]

[commands]
pre-install = """
  yarn install
"""
install = """
  yarn create redwood-app ./${project name}
"""
post-install = """
  echo "post install"
"""
