path = '/' # defaults to /
queries = [
  'project name' # optional regex validation
]
replacements = [
  'TODO'
]

[commands]
pre-install = """
  yarn install
  yarn add
  echo \"hello from pre-install\"
"""
install = """
  echo \"hello from install\"
""" # yarn create redwood-app ./${project name}
post-install = """
  echo \"hello from post-install\"
"""
